BEGIN TRANSACTION;
DROP TABLE IF EXISTS street;

CREATE TABLE street (
  id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  side VARCHAR(50) NOT NULL,
  neighborhood VARCHAR(50) NOT NULL,
  start_month int NOT NULL, --1=January, 2=February, ... 12=December
  end_month int NOT NULL, --1=January, 2=February, ... 12=December
  cleaning_day INT NOT NULL,--1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday, 7=Sunday
  cleaning_week INT NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  
  
  constraint id primary key (id),
  CONSTRAINT cleaning_day_check CHECK ((cleaning_day = 1) OR (cleaning_day = 2) OR (cleaning_day = 3) OR (cleaning_day = 4) OR (cleaning_day = 5) OR (cleaning_day = 6) OR (cleaning_day = 7)),
  CONSTRAINT cleaning_week_check CHECK ((cleaning_week = 1) OR (cleaning_week = 2) OR (cleaning_week = 3) OR (cleaning_week = 4)),
  CONSTRAINT start_month_check CHECK ((start_month = 1) OR (start_month = 2) OR (start_month = 3) OR (start_month = 4)OR (start_month = 5)OR (start_month = 6)OR (start_month = 7)OR (start_month = 8)OR (start_month = 9)OR (start_month = 10)OR (start_month = 11)OR (start_month = 12)),
  CONSTRAINT end_month_check CHECK ((end_month = 1) OR (end_month = 2) OR (end_month = 3) OR (end_month = 4)OR (end_month = 5)OR (end_month = 6)OR (end_month = 7)OR (end_month = 8)OR (end_month = 9)OR (end_month = 10)OR (end_month = 11)OR (end_month = 12))

);

INSERT INTO street (name, side, neighborhood, start_month, end_month, cleaning_week, cleaning_day, start_time, end_time)
VALUES ('Pennsylvania Avenue', 'even', 'North Side', 4, 12, 1, 4, '08:30:00', '14:00:00');

INSERT INTO street (name, side, neighborhood, start_month, end_month, cleaning_week, cleaning_day, start_time, end_time)
VALUES ('Allegheny Avenue', 'odd', 'North Side', 4, 12, 2, 2, '08:30:00', '14:00:00');

INSERT INTO street (name, side, neighborhood, start_month, end_month, cleaning_week, cleaning_day, start_time, end_time)
VALUES ('Allegheny Avenue', 'even', 'North Side', 4, 12, 2, 1, '08:30:00', '14:00:00');

INSERT INTO street (name, side, neighborhood, start_month, end_month, cleaning_week, cleaning_day, start_time, end_time)
VALUES ('North Avenue', 'odd', 'North Side', 4, 12, 2, 1, '08:30:00', '14:00:00');


ROLLBACK;